// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"noneland/backend/interview/configs"
	"noneland/backend/interview/internal/api"
	"noneland/backend/interview/internal/db"
	"noneland/backend/interview/internal/pkg"
	"sync"
)

// Injectors from wire.go:

// NewAPI 構造真實的 API 實例
func NewAPI() (*api.API, error) {
	apiClient := NewExAPIClient()
	cache := pkg.NewCache()
	config := NewConfig()
	dbClient, err := NewDBClient(config)
	if err != nil {
		return nil, err
	}
	apiAPI := api.NewAPI(apiClient, cache, dbClient)
	return apiAPI, nil
}

// wire.go:

var (
	configOnce sync.Once
	cfg        *configs.Config

	dbOnce   sync.Once
	database *db.MySQLClient
)

// NewConfig 確保配置僅初始化一次
func NewConfig() *configs.Config {
	configOnce.Do(func() {
		cfg = configs.NewConfig()
	})
	return cfg
}

// NewDBClient 確保數據庫連接僅初始化一次
func NewDBClient(cfg2 *configs.Config) (db.DBClient, error) {
	var err error
	dbOnce.Do(func() {
		database, err = db.NewMySQLClient(cfg2.DSN)
	})
	return database, err
}

// NewExAPIClient 構造真實 API 客戶端
func NewExAPIClient() pkg.APIClient {
	return pkg.NewExAPIClient()
}
